"""macOS: poll NSPasteboard.changeCount (needs no Accessibility permission)."""
from __future__ import annotations

import threading

from privatecopy.watchers.base import ClipboardBackend, ClipboardEvent, OnChange

MARKER_TYPE = "org.privatecopy.redacted"
TRANSIENT_TYPE = "org.nspasteboard.TransientType"
# nspasteboard.org conventions used by password managers and clipboard tools.
CONCEALED_TYPES = ("org.nspasteboard.ConcealedType", TRANSIENT_TYPE, "org.nspasteboard.AutoGeneratedType")
POLL_SECONDS = 0.25


class MacClipboard(ClipboardBackend):
    name = "macos"

    def __init__(self) -> None:
        from AppKit import NSPasteboard, NSPasteboardTypeString

        self._pb = NSPasteboard.generalPasteboard()
        self._string_type = NSPasteboardTypeString
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def read_text(self) -> str | None:
        import objc

        with objc.autorelease_pool():
            text = self._pb.stringForType_(self._string_type)
            return None if text is None else str(text)

    def write_text(self, text: str, *, transient: bool = False) -> None:
        import objc

        with objc.autorelease_pool():
            types = [self._string_type, MARKER_TYPE] + ([TRANSIENT_TYPE] if transient else [])
            self._pb.declareTypes_owner_(types, None)  # clears every existing format
            self._pb.setString_forType_(text, self._string_type)
            self._pb.setString_forType_("1", MARKER_TYPE)
            if transient:
                self._pb.setString_forType_("", TRANSIENT_TYPE)

    def start(self, on_change: OnChange) -> None:
        self._stop.clear()
        self._thread = threading.Thread(target=self._poll, args=(on_change,),
                                        name="privatecopy-mac-clipboard", daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()

    def _poll(self, on_change: OnChange) -> None:
        import objc
        from AppKit import NSWorkspace

        last = self._pb.changeCount()
        while not self._stop.wait(POLL_SECONDS):
            with objc.autorelease_pool():
                count = self._pb.changeCount()
                if count == last:
                    continue
                last = count
                types = {str(t) for t in (self._pb.types() or [])}
                own = MARKER_TYPE in types
                concealed = any(t in types for t in CONCEALED_TYPES)
                text = None
                if not (own or concealed) and self._string_type in types:
                    raw = self._pb.stringForType_(self._string_type)
                    text = None if raw is None else str(raw)
                app = NSWorkspace.sharedWorkspace().frontmostApplication()
                source = f"{app.localizedName()} ({app.bundleIdentifier()})" if app else None
            try:
                on_change(ClipboardEvent(text, own=own, concealed=concealed, source_app=source))
            except Exception:
                pass  # the controller reports its own errors; keep polling
