"""Build step: render the user-facing text in scrubboard/texts.py into the files the
installers read, so the app, the installers and the download page all say the same thing.

  installer/build/text/win/messages.iss   Inno Setup [Messages] (welcome, pages, progress, finish)
  installer/build/text/win/disclaimer.txt Inno "must accept" page
  installer/build/text/win/howto.txt      Inno info page
  installer/build/text/mac/*.html         macOS Installer welcome / license / readme / conclusion
  --site DIR                              download page (docs/site/index.template.html) + icon
"""
import argparse
import html
import os
import shutil
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)

from scrubboard import texts  # noqa: E402

OUT = os.path.join(ROOT, "installer", "build", "text")
MAC_STYLE = ("<style>body{font:13px/1.5 -apple-system,sans-serif;color:#1d2b2a}"
             "h2{font-size:17px;color:#0f6b66;margin-top:0}code{font-size:12px}</style>")


def _inno(paragraphs: list[str]) -> str:
    """One Inno message value: no raw newlines (%n), and '%' escaped."""
    return "%n%n".join(p.replace("%", "%%") for p in paragraphs)


def windows() -> None:
    d = os.path.join(OUT, "win")
    os.makedirs(d, exist_ok=True)
    where = texts.icon_where("Windows")
    messages = {
        "WelcomeLabel1": texts.WELCOME_TITLE,
        "WelcomeLabel2": _inno([*texts.WELCOME_SHORT, "Click Next to continue."]),
        "WizardLicense": texts.DISCLAIMER_TITLE,
        "LicenseLabel": "Scrubboard helps, but it can miss things.",
        "LicenseLabel3": "Please read this. You need to accept it to continue.",
        "LicenseAccepted": texts.DISCLAIMER_ACCEPT,
        "LicenseNotAccepted": "I do not accept (setup will stop)",
        "WizardInfoBefore": texts.HOW_TO_TITLE,
        "InfoBeforeLabel": "Here's how you'll use Scrubboard every day.",
        "InfoBeforeClickLabel": "When you're ready, click Next.",
        "WizardSelectTasks": "A few choices",
        "SelectTasksDesc": "Choose how Scrubboard fits into your day. You can change these later.",
        "WizardReady": "Ready to install",
        "ReadyLabel1": "Scrubboard is ready to be installed. It only takes a moment and doesn't need "
                       "an internet connection.",
        "InstallingLabel": "Scrubboard and its privacy detector (about 480 MB) are being copied onto this "
                           "computer. The privacy detector is the part that recognizes names and other "
                           "identifying details. It runs only on this computer and never sends anything "
                           "over the internet.",
        "StatusExtractFiles": "Copying Scrubboard and its privacy detector onto this computer...",
        "StatusCreateIcons": "Creating the Scrubboard shortcuts...",
        "StatusCreateRegistryEntries": "Saving your choices...",
        "StatusSavingUninstall": "Saving the information needed to remove Scrubboard later...",
        "WizardInstalling": "Installing Scrubboard",
        "FinishedHeadingLabel": "Scrubboard is installed",
        "FinishedLabelNoIcons": _inno([f"Scrubboard runs quietly in the background. Its icon is {where}.",
                                       "Copy text, click the Scrubboard icon, then paste. "
                                       "Read the cleaned text before you share it."]),
        "FinishedLabel": _inno([f"Scrubboard runs quietly in the background. Its icon is {where}.",
                                "Copy text, click the Scrubboard icon, then paste. "
                                "Read the cleaned text before you share it."]),
        "ClickFinish": "Click Finish to close this window.",
    }
    with open(os.path.join(d, "messages.iss"), "w", encoding="utf-8-sig") as f:
        f.write("; Generated by installer/render_texts.py from scrubboard/texts.py. Do not edit.\n[Messages]\n")
        for key, value in messages.items():
            f.write(f"{key}={value}\n")
    with open(os.path.join(d, "disclaimer.txt"), "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write(texts.to_text([texts.DISCLAIMER_TITLE.upper(), *texts.DISCLAIMER]) + "\n")
    with open(os.path.join(d, "howto.txt"), "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write(texts.to_text([*texts.WELCOME, texts.HOW_TO_TITLE.upper(), *texts.how_to("Windows")]) + "\n")


def mac() -> None:
    d = os.path.join(OUT, "mac")
    os.makedirs(d, exist_ok=True)
    pages = {
        "welcome.html": (texts.WELCOME_TITLE, texts.WELCOME),
        "license.html": (texts.DISCLAIMER_TITLE, texts.DISCLAIMER),
        "readme.html": (texts.HOW_TO_TITLE, texts.how_to("Darwin")),
        "conclusion.html": ("Scrubboard is installed", [
            f"Scrubboard is running. Its icon is {texts.icon_where('Darwin')}. "
            "It also starts by itself when you log in.",
            f"To clean text: select it, right-click, and choose Services → \"{texts.SERVICE_TITLE}\". "
            "Then paste.",
            "If the Services item doesn't show up yet, log out and back in once.",
            "Always read the cleaned text before you share it.",
        ]),
    }
    for name, (title, paragraphs) in pages.items():
        with open(os.path.join(d, name), "w", encoding="utf-8") as f:
            f.write(f"<!doctype html><html><head><meta charset='utf-8'>{MAC_STYLE}</head><body>"
                    f"{texts.to_html(title, paragraphs)}</body></html>\n")


def site(dest: str) -> None:
    os.makedirs(dest, exist_ok=True)
    with open(os.path.join(ROOT, "docs", "site", "index.template.html"), encoding="utf-8") as f:
        page = f.read()
    for key, value in {
        "WELCOME": texts.to_html("What it does", texts.WELCOME),
        "DISCLAIMER": texts.to_html(texts.DISCLAIMER_TITLE, texts.DISCLAIMER),
        "SERVICE_TITLE": html.escape(texts.SERVICE_TITLE),
        "EXAMPLE_BEFORE": html.escape(texts.EXAMPLE_BEFORE),
        "EXAMPLE_AFTER": html.escape(texts.EXAMPLE_AFTER),
    }.items():
        page = page.replace("{{" + key + "}}", value)
    with open(os.path.join(dest, "index.html"), "w", encoding="utf-8") as f:
        f.write(page)
    shutil.copy(os.path.join(ROOT, "assets", "scrubboard-256.png"), dest)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--site", metavar="DIR", help="only render the download page into DIR")
    args = parser.parse_args()
    if args.site:
        site(args.site)
        print(f"-> {args.site}")
    else:
        windows()
        mac()
        print(f"-> {OUT}")
